services:
  demo:
  kml:
  tms:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is the fantastic MapProxy.
      online_resource: http://mapproxy.org/

layers:
  - name: base
    title: Basiskarte
    sources: [mycache]
  - name: pubtrans
    title: ÖPNV-Haltestellen
    sources: [mycache]
  - name: poi
    title: Points of Interest
    sources: [mycache]
  - name: boundaries
    title: Gebietsgrenzen
    sources: [mycache]
  - name: ways
    title: Wege
    sources: [mycache]


caches:
  mycache:
    cache:
      type: file
      directory: /usr/local/mapproxy/cache_data
    grids: [tile_grid_of_source]
    sources: [my_tile_source]

sources:
  my_tile_source:
    type: tile
    grid: tile_grid_of_source
    url: https://tile.openstreetmap.org/%(z)s/%(x)s/%(y)s.png

grids:
  tile_grid_of_source:
    base: GLOBAL_MERCATOR
    origin: nw

globals:
  image:
      resampling_method: bicubic

